### ISSUE TITLE
Why are the function calls not highlighted?

### ISSUE THREAD

**Issue by ankitrg** [atom/language-ruby-on-rails#53]
Here I am attaching a screenshot from atom and vscode, and in atom the function calls are not highlighted.

Atom:
[IMG]http://i66.tinypic.com/2q8vssp.png[/IMG]

VsCode:
[IMG]http://i68.tinypic.com/573a9.png[/IMG]

**Comment by darrenterhune** [comment]
Sounds like something for the discussion board https://discuss.atom.io

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by ankitrg** [comment]
Oh, I thought it would be a missing feature or a bug. I will ask this again on the forum.
